apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresqldb-clients
  name: postgresqldb-clients
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresqldb-clients
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresqldb-clients
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: clientservice
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          imagePullPolicy: ""
          name: postgresqldb-clients
          ports:
            - containerPort: 5432
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data-clients
          persistentVolumeClaim:
            claimName: postgres-data-clients
status: { }