apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: clientservice
  name: clientservice
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: clientservice
status:
  loadBalancer: { }